require("plugins.ui.colorscheme")
require("plugins.ui.lualine")
require("plugins.ui.bufferline")
require("plugins.ui.indent-blankline")
require("plugins.ui.nvim-colorizer")
require("plugins.ui.todo-comments")
